version: '3.9'

services:
  web:
    image: php:7.4-fpm
    container_name: php-fpm
    volumes:
      - ./src:/var/www/html
    networks:
      - prestashop
  mysql:
    image: mysql:8
    container_name: prestashop-db
    environment:
      MYSQL_DATABASE: prestashop
      MYSQL_ROOT_PASSWORD: prestashop
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
      - ./prestashop_backup.sql:/docker-entrypoint-initdb.d/prestashop_backup.sql
    networks:
      - prestashop

  prestashop:
    build:
      context: ./ssl
      dockerfile: Dockerfile
    container_name: prestashop
    environment:
      DB_SERVER: mysql
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    networks:
      - prestashop

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: prestashop
    ports:
      - 8081:80
    depends_on:
      - mysql
    networks:
      - prestashop

networks:
  prestashop:

volumes:
  db_data:

