version: '3.9'

services:
  mysql:
    image: mysql:8
    container_name: prestashop-db
    environment:
      MYSQL_DATABASE: prestashop
      MYSQL_ROOT_PASSWORD: prestashop
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
      - ./prestashop_backup.sql:/docker-entrypoint-initdb.d/prestashop_backup.sql
    networks:
      - prestashop

  prestashop:
    image: prestashop/prestashop:1.7.8
    container_name: prestashop
    environment:
      DB_SERVER: mysql
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    networks:
      - prestashop
    command: /bin/bash -c "chown -R www-data:www-data /var/www/html && find /var/www/html -type d -exec chmod 755 {} \; && find /var/www/html -type f -exec chmod 644 {} \; && apache2-foreground"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: prestashop
    ports:
      - 8081:80
    depends_on:
      - mysql
    networks:
      - prestashop

networks:
  prestashop:

volumes:
  db_data:

