parent: classic
name: child_classic
display_name: crochet theme
version: 0.0.2
assets:
  use_parent_assets: true
author:
  name: CrochetDevs Team
  email: "rozrywka22@outlook.com"
  url: "https://github.com/jwalasik3/BiznesElektroniczny"